/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type ContributionStruct = {
  contributor: AddressLike;
  amount: BigNumberish;
};

export type ContributionStructOutput = [contributor: string, amount: bigint] & {
  contributor: string;
  amount: bigint;
};

export interface IPoolDeposit2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "depositNative"
      | "depositToken"
      | "individualDeposit"
      | "pooledDeposit"
      | "pooledDepositNative"
      | "pooledDepositToken"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Deposit" | "PooledDeposit"): EventFragment;

  encodeFunctionData(
    functionFragment: "depositNative",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositToken",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "individualDeposit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pooledDeposit",
    values: [ContributionStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "pooledDepositNative",
    values: [ContributionStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "pooledDepositToken",
    values: [ContributionStruct[], AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "individualDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pooledDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pooledDepositNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pooledDepositToken",
    data: BytesLike
  ): Result;
}

export namespace DepositEvent {
  export type InputTuple = [
    id: string,
    trader: AddressLike,
    amount: BigNumberish,
    token: AddressLike,
    poolId: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    trader: string,
    amount: bigint,
    token: string,
    poolId: bigint
  ];
  export interface OutputObject {
    id: string;
    trader: string;
    amount: bigint;
    token: string;
    poolId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PooledDepositEvent {
  export type InputTuple = [
    id: BigNumberish,
    amount: BigNumberish,
    token: AddressLike
  ];
  export type OutputTuple = [id: bigint, amount: bigint, token: string];
  export interface OutputObject {
    id: bigint;
    amount: bigint;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPoolDeposit2 extends BaseContract {
  connect(runner?: ContractRunner | null): IPoolDeposit2;
  waitForDeployment(): Promise<this>;

  interface: IPoolDeposit2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  depositNative: TypedContractMethod<
    [contributor: AddressLike],
    [void],
    "payable"
  >;

  depositToken: TypedContractMethod<
    [contributor: AddressLike, amount: BigNumberish, token: AddressLike],
    [void],
    "nonpayable"
  >;

  individualDeposit: TypedContractMethod<
    [contributor: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  pooledDeposit: TypedContractMethod<
    [contributions: ContributionStruct[]],
    [void],
    "nonpayable"
  >;

  pooledDepositNative: TypedContractMethod<
    [contributions: ContributionStruct[]],
    [void],
    "payable"
  >;

  pooledDepositToken: TypedContractMethod<
    [contributions: ContributionStruct[], token: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "depositNative"
  ): TypedContractMethod<[contributor: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "depositToken"
  ): TypedContractMethod<
    [contributor: AddressLike, amount: BigNumberish, token: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "individualDeposit"
  ): TypedContractMethod<
    [contributor: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pooledDeposit"
  ): TypedContractMethod<
    [contributions: ContributionStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pooledDepositNative"
  ): TypedContractMethod<
    [contributions: ContributionStruct[]],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "pooledDepositToken"
  ): TypedContractMethod<
    [contributions: ContributionStruct[], token: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "PooledDeposit"
  ): TypedContractEvent<
    PooledDepositEvent.InputTuple,
    PooledDepositEvent.OutputTuple,
    PooledDepositEvent.OutputObject
  >;

  filters: {
    "Deposit(string,address,uint256,address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "PooledDeposit(uint256,uint256,address)": TypedContractEvent<
      PooledDepositEvent.InputTuple,
      PooledDepositEvent.OutputTuple,
      PooledDepositEvent.OutputObject
    >;
    PooledDeposit: TypedContractEvent<
      PooledDepositEvent.InputTuple,
      PooledDepositEvent.OutputTuple,
      PooledDepositEvent.OutputObject
    >;
  };
}
