/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RabbitUInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "authorizeVault"
      | "authorizedVaults"
      | "changeSigner"
      | "defaultToken"
      | "deposit"
      | "depositNative"
      | "depositToken"
      | "eip712Domain"
      | "external_signer"
      | "getVersion"
      | "initialize"
      | "minDeposits"
      | "owner"
      | "processedWithdrawals"
      | "proxiableUUID"
      | "renounceOwnership"
      | "revokeVault"
      | "supportToken"
      | "supportedTokens"
      | "timelock"
      | "transferOwnership"
      | "unsupportToken"
      | "upgradeToAndCall"
      | "withdraw"
      | "withdrawNative"
      | "withdrawToVault"
      | "withdrawToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuthorizeVault"
      | "Deposit"
      | "EIP712DomainChanged"
      | "Initialized"
      | "OwnershipTransferred"
      | "RevokeVault"
      | "SetOwner"
      | "SetSigner"
      | "SupportToken"
      | "UnsupportToken"
      | "Upgraded"
      | "VaultWithdrawal"
      | "WithdrawalReceipt"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedVaults",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "changeSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositNative",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositToken",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "external_signer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      AddressLike[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "minDeposits",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processedWithdrawals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportToken",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "timelock", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unsupportToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawNative",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawToVault",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawToken",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "external_signer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVersion", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processedWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timelock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unsupportToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToken",
    data: BytesLike
  ): Result;
}

export namespace AuthorizeVaultEvent {
  export type InputTuple = [vault: AddressLike];
  export type OutputTuple = [vault: string];
  export interface OutputObject {
    vault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [
    id: string,
    trader: AddressLike,
    amount: BigNumberish,
    token: AddressLike
  ];
  export type OutputTuple = [
    id: string,
    trader: string,
    amount: bigint,
    token: string
  ];
  export interface OutputObject {
    id: string;
    trader: string;
    amount: bigint;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevokeVaultEvent {
  export type InputTuple = [vault: AddressLike];
  export type OutputTuple = [vault: string];
  export interface OutputObject {
    vault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetOwnerEvent {
  export type InputTuple = [owner: AddressLike];
  export type OutputTuple = [owner: string];
  export interface OutputObject {
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetSignerEvent {
  export type InputTuple = [signer: AddressLike];
  export type OutputTuple = [signer: string];
  export interface OutputObject {
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SupportTokenEvent {
  export type InputTuple = [token: AddressLike, minDeposit: BigNumberish];
  export type OutputTuple = [token: string, minDeposit: bigint];
  export interface OutputObject {
    token: string;
    minDeposit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnsupportTokenEvent {
  export type InputTuple = [token: AddressLike];
  export type OutputTuple = [token: string];
  export interface OutputObject {
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultWithdrawalEvent {
  export type InputTuple = [
    vault: AddressLike,
    receiver: AddressLike,
    asset: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    receiver: string,
    asset: string,
    amount: bigint
  ];
  export interface OutputObject {
    vault: string;
    receiver: string;
    asset: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalReceiptEvent {
  export type InputTuple = [
    id: BigNumberish,
    trader: AddressLike,
    amount: BigNumberish,
    token: AddressLike
  ];
  export type OutputTuple = [
    id: bigint,
    trader: string,
    amount: bigint,
    token: string
  ];
  export interface OutputObject {
    id: bigint;
    trader: string;
    amount: bigint;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RabbitU extends BaseContract {
  connect(runner?: ContractRunner | null): RabbitU;
  waitForDeployment(): Promise<this>;

  interface: RabbitUInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  authorizeVault: TypedContractMethod<
    [vault: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedVaults: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  changeSigner: TypedContractMethod<
    [new_signer: AddressLike],
    [void],
    "nonpayable"
  >;

  defaultToken: TypedContractMethod<[], [string], "view">;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  depositNative: TypedContractMethod<[], [void], "payable">;

  depositToken: TypedContractMethod<
    [amount: BigNumberish, token: AddressLike],
    [void],
    "nonpayable"
  >;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  external_signer: TypedContractMethod<[], [string], "view">;

  getVersion: TypedContractMethod<[], [bigint], "view">;

  initialize: TypedContractMethod<
    [
      _timelock: AddressLike,
      _owner: AddressLike,
      _signer: AddressLike,
      _defaultToken: AddressLike,
      _minDeposit: BigNumberish,
      _otherTokens: AddressLike[],
      _minDeposits: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  minDeposits: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  processedWithdrawals: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeVault: TypedContractMethod<[vault: AddressLike], [void], "nonpayable">;

  supportToken: TypedContractMethod<
    [token: AddressLike, minDeposit: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportedTokens: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  timelock: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unsupportToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  withdraw: TypedContractMethod<
    [
      id: BigNumberish,
      trader: AddressLike,
      amount: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  withdrawNative: TypedContractMethod<
    [
      id: BigNumberish,
      trader: AddressLike,
      amount: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  withdrawToVault: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, receiver: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawToken: TypedContractMethod<
    [
      id: BigNumberish,
      trader: AddressLike,
      amount: BigNumberish,
      token: AddressLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "authorizeVault"
  ): TypedContractMethod<[vault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedVaults"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "changeSigner"
  ): TypedContractMethod<[new_signer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "defaultToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositNative"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "depositToken"
  ): TypedContractMethod<
    [amount: BigNumberish, token: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "external_signer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getVersion"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _timelock: AddressLike,
      _owner: AddressLike,
      _signer: AddressLike,
      _defaultToken: AddressLike,
      _minDeposit: BigNumberish,
      _otherTokens: AddressLike[],
      _minDeposits: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "minDeposits"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processedWithdrawals"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeVault"
  ): TypedContractMethod<[vault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportToken"
  ): TypedContractMethod<
    [token: AddressLike, minDeposit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportedTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "timelock"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unsupportToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      trader: AddressLike,
      amount: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawNative"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      trader: AddressLike,
      amount: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawToVault"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, receiver: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawToken"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      trader: AddressLike,
      amount: BigNumberish,
      token: AddressLike,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AuthorizeVault"
  ): TypedContractEvent<
    AuthorizeVaultEvent.InputTuple,
    AuthorizeVaultEvent.OutputTuple,
    AuthorizeVaultEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RevokeVault"
  ): TypedContractEvent<
    RevokeVaultEvent.InputTuple,
    RevokeVaultEvent.OutputTuple,
    RevokeVaultEvent.OutputObject
  >;
  getEvent(
    key: "SetOwner"
  ): TypedContractEvent<
    SetOwnerEvent.InputTuple,
    SetOwnerEvent.OutputTuple,
    SetOwnerEvent.OutputObject
  >;
  getEvent(
    key: "SetSigner"
  ): TypedContractEvent<
    SetSignerEvent.InputTuple,
    SetSignerEvent.OutputTuple,
    SetSignerEvent.OutputObject
  >;
  getEvent(
    key: "SupportToken"
  ): TypedContractEvent<
    SupportTokenEvent.InputTuple,
    SupportTokenEvent.OutputTuple,
    SupportTokenEvent.OutputObject
  >;
  getEvent(
    key: "UnsupportToken"
  ): TypedContractEvent<
    UnsupportTokenEvent.InputTuple,
    UnsupportTokenEvent.OutputTuple,
    UnsupportTokenEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "VaultWithdrawal"
  ): TypedContractEvent<
    VaultWithdrawalEvent.InputTuple,
    VaultWithdrawalEvent.OutputTuple,
    VaultWithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalReceipt"
  ): TypedContractEvent<
    WithdrawalReceiptEvent.InputTuple,
    WithdrawalReceiptEvent.OutputTuple,
    WithdrawalReceiptEvent.OutputObject
  >;

  filters: {
    "AuthorizeVault(address)": TypedContractEvent<
      AuthorizeVaultEvent.InputTuple,
      AuthorizeVaultEvent.OutputTuple,
      AuthorizeVaultEvent.OutputObject
    >;
    AuthorizeVault: TypedContractEvent<
      AuthorizeVaultEvent.InputTuple,
      AuthorizeVaultEvent.OutputTuple,
      AuthorizeVaultEvent.OutputObject
    >;

    "Deposit(string,address,uint256,address)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RevokeVault(address)": TypedContractEvent<
      RevokeVaultEvent.InputTuple,
      RevokeVaultEvent.OutputTuple,
      RevokeVaultEvent.OutputObject
    >;
    RevokeVault: TypedContractEvent<
      RevokeVaultEvent.InputTuple,
      RevokeVaultEvent.OutputTuple,
      RevokeVaultEvent.OutputObject
    >;

    "SetOwner(address)": TypedContractEvent<
      SetOwnerEvent.InputTuple,
      SetOwnerEvent.OutputTuple,
      SetOwnerEvent.OutputObject
    >;
    SetOwner: TypedContractEvent<
      SetOwnerEvent.InputTuple,
      SetOwnerEvent.OutputTuple,
      SetOwnerEvent.OutputObject
    >;

    "SetSigner(address)": TypedContractEvent<
      SetSignerEvent.InputTuple,
      SetSignerEvent.OutputTuple,
      SetSignerEvent.OutputObject
    >;
    SetSigner: TypedContractEvent<
      SetSignerEvent.InputTuple,
      SetSignerEvent.OutputTuple,
      SetSignerEvent.OutputObject
    >;

    "SupportToken(address,uint256)": TypedContractEvent<
      SupportTokenEvent.InputTuple,
      SupportTokenEvent.OutputTuple,
      SupportTokenEvent.OutputObject
    >;
    SupportToken: TypedContractEvent<
      SupportTokenEvent.InputTuple,
      SupportTokenEvent.OutputTuple,
      SupportTokenEvent.OutputObject
    >;

    "UnsupportToken(address)": TypedContractEvent<
      UnsupportTokenEvent.InputTuple,
      UnsupportTokenEvent.OutputTuple,
      UnsupportTokenEvent.OutputObject
    >;
    UnsupportToken: TypedContractEvent<
      UnsupportTokenEvent.InputTuple,
      UnsupportTokenEvent.OutputTuple,
      UnsupportTokenEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "VaultWithdrawal(address,address,address,uint256)": TypedContractEvent<
      VaultWithdrawalEvent.InputTuple,
      VaultWithdrawalEvent.OutputTuple,
      VaultWithdrawalEvent.OutputObject
    >;
    VaultWithdrawal: TypedContractEvent<
      VaultWithdrawalEvent.InputTuple,
      VaultWithdrawalEvent.OutputTuple,
      VaultWithdrawalEvent.OutputObject
    >;

    "WithdrawalReceipt(uint256,address,uint256,address)": TypedContractEvent<
      WithdrawalReceiptEvent.InputTuple,
      WithdrawalReceiptEvent.OutputTuple,
      WithdrawalReceiptEvent.OutputObject
    >;
    WithdrawalReceipt: TypedContractEvent<
      WithdrawalReceiptEvent.InputTuple,
      WithdrawalReceiptEvent.OutputTuple,
      WithdrawalReceiptEvent.OutputObject
    >;
  };
}
