/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBlastPoints,
  IBlastPointsInterface,
} from "../../../contracts/BfxDepositU.sol/IBlastPoints";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    name: "configurePointsOperator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBlastPoints__factory {
  static readonly abi = _abi;
  static createInterface(): IBlastPointsInterface {
    return new Interface(_abi) as IBlastPointsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBlastPoints {
    return new Contract(address, _abi, runner) as unknown as IBlastPoints;
  }
}
