/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRabbitX,
  IRabbitXInterface,
} from "../../../contracts/Vault7540.sol/IRabbitX";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
    ],
    name: "withdrawToVault",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRabbitX__factory {
  static readonly abi = _abi;
  static createInterface(): IRabbitXInterface {
    return new Interface(_abi) as IRabbitXInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IRabbitX {
    return new Contract(address, _abi, runner) as unknown as IRabbitX;
  }
}
